# Generated by Django 4.2.26 on 2025-11-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collect_app", "0002_alter_collect_options_alter_comment_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collect",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="Сбор активен"),
        ),
    ]
