# Generated by Django 4.2.26 on 2025-11-10 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect_app', '0003_alter_collect_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='collect',
            name='closure_requested',
            field=models.BooleanField(default=False, verbose_name='Запрошено закрытие'),
        ),
        migrations.AddField(
            model_name='collect',
            name='payment_details',
            field=models.CharField(default='', max_length=200, verbose_name='Реквизиты для перевода (карта/счет)'),
            preserve_default=False,
        ),
    ]
