# Generated by Django 4.2.26 on 2025-11-10 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect_app', '0004_collect_closure_requested_collect_payment_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collect',
            name='end_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания сбора'),
        ),
    ]
