# Generated by Django 4.2.26 on 2025-11-11 09:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect_app', '0005_alter_collect_end_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collect',
            name='payment_details',
        ),
        migrations.AddField(
            model_name='collect',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(20)], verbose_name='Номер счёта'),
        ),
        migrations.AddField(
            model_name='collect',
            name='bank_bik',
            field=models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.MinLengthValidator(9)], verbose_name='БИК банка'),
        ),
        migrations.AddField(
            model_name='collect',
            name='bank_inn',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='ИНН банка'),
        ),
        migrations.AddField(
            model_name='collect',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование банка'),
        ),
        migrations.AddField(
            model_name='collect',
            name='card_number',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator('^[245]\\d{15}$', 'Номер карты должен состоять из 16 цифр и начинаться с 2, 4 или 5.')], verbose_name='Номер карты'),
        ),
        migrations.AddField(
            model_name='collect',
            name='payment_type',
            field=models.CharField(choices=[('card', 'Карта'), ('account', 'Банковский счёт')], default='card', max_length=10, verbose_name='Тип реквизитов'),
        ),
        migrations.AddField(
            model_name='collect',
            name='recipient_name',
            field=models.CharField(default='Не указано', max_length=255, verbose_name='ФИО получателя / Название организации'),
        ),
    ]
