# Generated by Django 4.2.26 on 2025-11-11 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect_app', '0006_remove_collect_payment_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collect',
            name='occasion_other_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Уточните повод'),
        ),
        migrations.AlterField(
            model_name='collect',
            name='end_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время окончания сбора'),
        ),
        migrations.AlterField(
            model_name='collect',
            name='occasion',
            field=models.CharField(choices=[('birthday', 'День рождения'), ('wedding', 'Свадьба'), ('charity', 'Благотворительность'), ('travel', 'Путешествие'), ('project', 'Проект'), ('other', 'Другое')], max_length=20, verbose_name='Повод'),
        ),
    ]
